version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  pizza-app:
    build: .
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    environment:
      - LLM_MODE=local  # or "cloud" or "auto"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  ollama-data:

