services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama ps"]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 60s
    networks: # Should be indented to align with 'image', 'ports', etc.
      - pizza_network

  pizza-app:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
    networks: # Should be indented to align with 'build', 'ports', etc.
      - pizza_network

volumes: # This is a top-level key, so it should have no preceding spaces
  ollama-data:

networks: # This is a top-level key, so it should have no preceding spaces
  pizza_network:
    driver: bridge